version: "3.9"
services:
    converter:
        build:
            context: .
            dockerfile: PdfTronDwgToPdf/Dockerfile
        volumes:
            - ./PdfTronDwgToPdf/in:/app/in/
            - ./PdfTronDwgToPdf/out:/app/out/
                
     
            